---
title: "NEWS"
output: github_document
---

# SSDM 0.1.9026 
- checkargs
- stack_modelling cores
- NEWS & README

# SSDM 0.1.9025 
Dimitri Justeau: endemism parameter bug in the gui fixed

# SSDM 0.1.9024 
- Enable host and port option when launching the gui [Dimitri Justeau](https://github.com/dimitri-justeau)
- README

# SSDM 0.1.9023 
- tmmpath in stack_modelling()
- split with '.Ensemble.SDM' instead of '.' in save, plot, and gui

# SSDM 0.1.9022 
- ESDM list in plot.model bug fixed

# SSDM 0.1.9021 
- CRAN second submit changes

# SSDM 0.1.9020 
- CRAN first submit changes

# SSDM 0.1.9019 
- Occurrences man url corrected
- Check -as--cran
- Check on CRAN win-build

# SSDM 0.1.9018 
- save tab in gui debug for ESDM (Jay)

# SSDM 0.1.9017 
- tmppath in ensemble_modelling dir creation (Jay)
- tmp doc in ensemble_ and stack_modelling [Florian de Boissieu](https://github.com/floriandeboissieu)

# SSDM 0.1.9016 
- Weighted endemism index major change : range definition
- load_occ major beug fixed, wrong rows were removed
- tmppath change in ensemble and stack_modelling (overwrite of path var issue) [Florian de Boissieu](https://github.com/floriandeboissieu)
- raster::readAll to force loading Env in memory (load_var) [Florian de Boissieu](https://github.com/floriandeboissieu)
- Raster[Raster[]<=-900]=NA instead of reclassify [Florian de Boissieu](https://github.com/floriandeboissieu)
- Resample with more condition to avoid extra computing [Florian de Boissieu](https://github.com/floriandeboissieu)
- Add timestampt to ensemble_modelling [Florian de Boissieu](https://github.com/floriandeboissieu)

# SSDM 0.1.9015
- n.cores parameter in GBM auto-adapted to parallel computing in stack_modelling
- gc() added at the end of each modelling function to avoid memory loss
- ensemble.AlgoSDM() weight corrected
- .cran-comment in .Rbuildignore
- shinyFiles in Suggests and checked when gui() is used
- Check with 0 Notes 0 Warnings 0 Errors

# SSDM 0.1.9014 
- Parallel computing with parallel::parLapply
- .csv in save_model [Dimitri Justeau](https://github.com/dimitri-justeau)
- Species in ./Species in save_stack [Dimitri Justeau](https://github.com/dimitri-justeau)
- Stack results in ./Stack in save_stack [Dimitri Justeau](https://github.com/dimitri-justeau)
- Pearson cor = NA or NULL in evaluate.axis

# SSDM 0.1.9013 
- Parallel computing: for loop correctly removed
- load_var tested

# SSDM 0.1.9012 
- Parallel computing for stack_modelling with parallel::mclapply

# SSDM 0.1.9011 
- load_var format and reso + extent bugged fixed [Dimitri Justeau](https://github.com/dimitri-justeau)

# SSDM 0.1.9010 
- uncertainties stack bug catch in try
- load_var with only folder path debug [Dimitri Justeau](https://github.com/dimitri-justeau)
- load_var parameter: factors -> categorical [Dimitri            Justeau](https://github.com/dimitri-justeau)
- Presence / absence occurrences modelling (Robin Pouteau)

# SSDM 0.1.9009 
-Stacking Algo. Corr. row names duplicate (strsplit)
- Duplicated '.tif' in load_occ doc[Dimitri Justeau](https://github.com/dimitri-justeau)
- Null supported by Spcol (default) in .checkargs [Dimitri Justeau](https://github.com/dimitri-justeau)

# SSDM 0.1.9008 
- Windows gui data input fix (default switch)

# SSDM 0.1.9007 
- load_occ porr data load improvement (occ not in spatial extent + less than 3 occ)

# SSDM 0.1.9006 
- ShinyApp structure in inst and shinyFiles working

# SSDM 0.1.9005 
- All inputs changed with shinyFiles package + Pcol text + Description (gui and pkg doc)

# SSDM 0.1.9004 
- Previous model input change (windows comptibilty)

# SSDM 0.1.0 
- Initial private beta release!
