# data(Env)
# data(Occurences)
# GLM = modelling('GLM', subset(Occurences, Occurences$genus == 'Ilex'), Env)
# ENM = ensemble_modelling('all', subset(Occurences, Occurences$genus == 'Ilex'), Env, name = 'Ilex', ensemble.thresh = c(0.6))
# stack = stack_modelling('all', Occurences, Env, Spcol = 'genus', cv = 'k-fold', cv.param = c(10,1), ensemble.thresh = c(0.6))
